// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"VIPArcher_SkipTitle","status":true,"description":"彻底跳过默认标题，包括事件里的返回标题和结束游戏时的返回","parameters":{"Test Only":"false"}}
];
